### PR TITLE
Add custom error message to custom error handler

### PR DESCRIPTION
**Pull request by MerzDaniel**
This pull requests provides the possibility to register custom errors along with a custom message. 

## Motivation
As a user of this library I want to have the possibility to register Errors of external libraries but provide a custom message. This releases me from catching certain errors and just wrapping them into local errors.

## Example
```
-------- ./service/bar-service.js
import { ExternalError, externalService } from 'external-lib'

registerError(ExternalError, 503, 'Connection to foo is not available')

function doServiceStuff() {
    externalService()
}
```

## Workaround using additional local express error handlers ("composition approach")
This workaround provides the same result but has two fallbacks:
* a lot more boilerplate code
* service local external errors force me to change my middleware implementations

```
-------- ./service/bar-service.js
import { externalService } from 'external-lib'

function doServiceStuff() {
    externalService()
}
-------- ./server.js
import { ExternalError } from 'external-lib'

class CustomExternalError extends Error {
   constructor(err) {
         super(err)
         this.message = 'Connection to foo is not available'
    }
}
registerError(CustomExternalError, 503)

app.use((err, req, res, next) => {
    if (err instanceof ExternalError) next(new CustomExternalError(err))
    else next(err)
})
app.use(expectedErrorHandler)
```

### CODE REVIEW

**Comment by pithu** [comment]
Questions:

1) What is the value for the caller of a static error message, isn't the class name of the error enough in that case ?

2) Are you sure that the name property of your ExternalError is set properly ? If not, you have to wrap the error anyway.

3) BTW the expectedErrorMiddleware is meant for 4XX error. Shouldn't be a general setup error be detected through the health route?

4) Imagine the next pull request, like a developer wants to have another property of the error in the message, like ```message = `Error with code ${error.code}` ```. Should we then add a fourth argument (eg constructErrorMessage) to the registerError function ?

5) Now imagine another pull request, like a developer get a native Error from an external library and wants to detect that (eg for the couchbase errors by the code property). Should we then add a fith argument to the registerError function like `detectError` ?

6) Imagine some more pull request that will come up .... should we add all these special cases ?

In my oppinion we should leave all that special stuff out of this module. This module must be very `stable` in terms of the package dependencies principles (see Clean Architecture book from uncle Bob). Therefore changes should be rare and reasonable for good reasons. We should follow the open/closed principle and do extensions for special cases outside the stable module.

The contract of this module is, that it exposes the class name and error message of expected 4XX error to the calling client. The class name of the error must be unique (i will add the missing check for that). Because the message is exposed to the client, it must be under the controll of the application for security reasons, i will make this more clear in the docs.

Special code should only run, where its required. We can either catch the error and rethrow a custom error like i would recommend for couchbase:

```
function wrappedGet() {
	try {
		couchbaseBucket.get(id)
	} (err) {
		if (err.code === errors.keyNotExist) {
			throw new CouchbaseKeyNotFoundError()
		}
		throw err
	}
}
```

Or do it in a middleware like you showed. IMO a bit more code is better then having API functions with a lot of arguments, for a lot of special cases.

**Comment by MerzDaniel** [comment]
Code above is only Pseudocode and should mainly show the idea

3. Why would you want to limit that? 

4. Of course a custom message creator callback that has the specific error as parameter could be an extension to my PR and also not bloat it too much. But for now nobody requested that so it's not needed
```
// message as string
registerError(CustomError, 503, 'customMessage')
// message as callback
registerError(CustomError, 503, err => `custom error ${err.message}`)
```

If my arguments don't convince you you can just reject the pull request. I don't care too much and currently I use my own middleware anyway.

**Comment by pithu** [comment]
If you are still not convinced ;) my proposal, if we really want to implement that, would be like that:

```
function registerError(errorClass, httpStatusCode, options = {}) {
   errorRegistry.set(errorClass.name, {
      // ...
      buildErrorMessage:  options.buildErrorMessage || err => err.message,
   }
   // ...

   // ...
   res.status(errorEntry.httpStatusCode).json({ message: errorEntry.buildErrorMessage(err) })
   // ...
```
so its more general, you can have static or dynamic custom error messages. And we can add more options in the future ...

**Comment by MerzDaniel** [comment]
The options object is an extension if more options come in in future. For now it is not to much needed in my opinion. I implemented it anyway. Still I kept the message as a shorthand as third parameter. So now registerError can be used as followed:
```
registerError(CustomError, 503, 'static error msg')
registerError(CustomError, 503, err => `dynamic msg ${err.message}`)
registerError(CustomError, 503, {
    httpResponseMsg: 'also here both variants are allowed',
})
```
We could think of moving all parameters or at least also the statusCode into the options object because the httpStatusCode is also optional just like the customMessage. 

To have overloaded function parameters as a convenience is quite common in a lot of public libraries. This makes it more handy to use them.

**Comment by pithu** [comment]
> To have overloaded function parameters as a convenience is quite common in a lot of public libraries.

Never heard about that, as far as i know the common way is to use option objects for that case. Compare  https://stackoverflow.com/questions/456177/function-overloading-in-javascript-best-practices and https://codeutopia.net/blog/2016/11/24/best-practices-for-javascript-function-parameters/

I would like to stick to that best practice. furthermore having a static error message seems to be a very rare use case (as already said above) i would not see it as a first top level option.

We do not live in the monolith anymore, where we can do major API changes all over the code base. Our API's should be stable, extendable and downward compatible. Therefore an option object for optional stuff is the best choice.

**Comment by MerzDaniel** [comment]
Closed - currently not needed

**Pull request closed without merging**
